sudo: required

language: generic

serivces:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t zpzgzerg/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true zpzgzerg/docker-react-app npm run test -- --coverage

#after_success:
#  - echo "Test Success!!"

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: docker-react-app
  env: Dockerreactapp-env
  bucket_name: elasticbeanstalk-ap-northeast-2-262840429927
  bucket_path: docker-react-app
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY